import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import SecondarySidebar from "@/components/SecondarySidebar";
import Head from "next/head";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/z.svg" />
      </Head>
      <body className="w-screen h-auto flex">
        <div className="flex gap-5">
          <SecondarySidebar />
          <Sidebar />
        </div>
    
        {children}
      </body>
    </html>
  );
}
